##################################################
#
#  Default Setting
#

#  -----------------------------------
#  Basic Setting
#

add_newline = true
scan_timeout = 1000
command_timeout = 1000
format = """\
    $hostname\
    $username\
    $kubernetes\
    $directory\
    $docker_context\
    $terraform\
    $aws\
    $env_var\
    $custom\
    $golang\
    $python\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $cmd_duration\
    $line_break\
    $battery\
    $time\
    $character\
    """

#  -----------------------------------
#  Character Setting
#

[character]
success_symbol = "[â¯â¯â¯](bold green)"
error_symbol = "[â¯â¯â¯](bold red)"

#  -----------------------------------
#  UserName Setting
#

[username]
format = "[${user} ]($style)"
style_user = "blue bold"
show_always = true

#  -----------------------------------
#  Directory Setting
#

[directory]
format = "[â¯ ${path} ]($style)"
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

##################################################
#
#  Git Setting
#

[git_branch]
format = "[â¯ ${symbol}${branch} ]($style)"
style = "bold purple"

[git_commit]
style = "bold green"

[git_status]
conflicted = "="
ahead = "î“"
behind = "î€"
diverged = "â‡•"
untracked = "ï„¨"
modified = "*"
renamed = "Â»"
deleted = "âœ˜"
style = "purple"


##################################################
#
#  Langage Setting
#

#  -----------------------------------
#  Docker
#

[docker_context]
format = "[â¯ ${symbol}${version}]($style) "
symbol = "ïŒˆ"
style = "bold blue"

#  -----------------------------------
#  Terraform
#

[terraform]
format = "[â¯ ${symbol}${version}]($style) "
#symbol = "ğŸ’ "
style = "bold 105"
detect_extensions = ["tf", "hcl"]

#  -----------------------------------
#  AWS
#

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "ï”­ "

[aws.region_aliases]
ap-northeast-1 = "Tokyo"

#  -----------------------------------
#  Golang
#

[golang]
format = "[â¯ ${symbol}${version}]($style) "
symbol = "î˜¦ "
style = "yellow bold"
disabled = false

#  -----------------------------------
#  Python
#

[python]
format = '[â¯ ${symbol}${version}( \(${virtualenv}\))]($style) '
symbol = "î˜† "
style = "yellow bold"
pyenv_version_name = false
pyenv_prefix = "pyenv "
python_binary = "python3"
